doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'Nikitades\ToxicAvenger\Infrastructure\Doctrine\Migration': '%kernel.project_dir%/src/Infrastructure/Doctrine/Migration/'
    enable_profiler: '%kernel.debug%'
