<?php

declare(strict_types=1);

namespace Nikitades\ToxicAvenger\Domain;

use Nikitades\ToxicAvenger\Domain\Entity\BadWordLibraryRecord;
use Nikitades\ToxicAvenger\Domain\Repository\BadWordLibraryRecordRepositoryInterface;
use Symfony\Component\Uid\Uuid;

class BadWordsLibrary
{
    private const OBSCENE_WORDS_ID_NAMESPACE = '7df363e4-b17d-44dc-b87c-9d2aba4f46d3';

    public function __construct(
        private BadWordLibraryRecordRepositoryInterface $badWordLibraryRecordRepository,
        private LemmatizerInterface $lemmatizer,
    ) {
    }

    /**
     * @param array<string> $lemmas
     * @return array<BadWordLibraryRecord>
     */
    public function getForChat(int $telegramChatId, array $lemmas): array
    {
        $foundFromDb = $this->badWordLibraryRecordRepository->findManyInChatFromList(
            chatId: $telegramChatId,
            possibleBadWordLemmas: $lemmas,
        );

        $notFoundInDbLemmas = array_diff($lemmas, array_map(fn (BadWordLibraryRecord $bwlr): string => $bwlr->text, $foundFromDb));

        $foundFromHardcodedLibrary = $this->findInHardcodedLibrary(
            telegramChatId: $telegramChatId,
            lemmas: $notFoundInDbLemmas,
        );

        $notFoundInHardcodedLibaryLemmas = array_diff($notFoundInDbLemmas, array_map(fn (BadWordLibraryRecord $bwlr): string => $bwlr->text, $foundFromHardcodedLibrary));

        $foundFromObsceneAnalysis = array_map(
            fn (string $obsceneLemma): BadWordLibraryRecord => new BadWordLibraryRecord(
                id: Uuid::v5(Uuid::fromString(self::OBSCENE_WORDS_ID_NAMESPACE), $obsceneLemma),
                telegramChatId: $telegramChatId,
                telegramMessageId: null,
                text: $obsceneLemma,
                active: true,
                updatedAt: null,
            ),
            $this->lemmatizer->findObsceneLemmas($notFoundInHardcodedLibaryLemmas),
        );

        $summaryData = [
            ...$foundFromDb,
            ...$foundFromHardcodedLibrary,
            ...$foundFromObsceneAnalysis,
        ];

        $uniqueData = array_combine(
            array_map(
                fn (BadWordLibraryRecord $record): string => $record->text,
                $summaryData,
            ),
            $summaryData,
        );

        return array_values($uniqueData);
    }

    /**
     * @param array<Uuid> $badWorldLibraryRecordIds
     * @return array<BadWordLibraryRecord>
     */
    public function findManyById(array $badWorldLibraryRecordIds): array
    {
        $itemsFromDatabase = $this->badWordLibraryRecordRepository->findManyById($badWorldLibraryRecordIds);

        $itemsFromDatabase = array_filter(
            $itemsFromDatabase,
            fn (BadWordLibraryRecord $bwlr): bool => $bwlr->active,
        );

        $hardcodedItems = array_filter(
            $this->getHardcodedItems(),
            fn (BadWordLibraryRecord $bwlr): bool => in_array(
                (string) $bwlr->id,
                array_map(
                    fn (Uuid $badWorldLibraryRecordId): string => (string) $badWorldLibraryRecordId,
                    $badWorldLibraryRecordIds,
                ),
                true,
            ),
        );

        return array_merge(
            $itemsFromDatabase,
            $hardcodedItems,
        );
    }

    /**
     * @param array<string> $lemmas
     * @return array<BadWordLibraryRecord>
     */
    private function findInHardcodedLibrary(int $telegramChatId, array $lemmas): array
    {
        $sourceWords = $this->getHardcodedItems($telegramChatId);

        $hardcodedBadWordsMap = [];
        foreach ($sourceWords as $sourceWord) {
            $hardcodedBadWordsMap[$sourceWord->text] = $sourceWord;
        }

        $output = [];
        foreach ($lemmas as $lemma) {
            if ('пуджом' === $lemma) {
                $lemma = 'пуджа';
            }
            $hardcodedBadWord = $hardcodedBadWordsMap[$lemma] ?? null;
            if (null == $hardcodedBadWord) {
                continue;
            }

            $output[] = $hardcodedBadWordsMap[$lemma];
        }

        return $output;
    }

    /**
     * @return array<BadWordLibraryRecord>
     */
    private function getHardcodedItems(?int $telegramChatId = null): array
    {
        return [
            new BadWordLibraryRecord(
                id: Uuid::fromString('6286c7fe-6bb1-4427-8b23-6e584b0729be'),
                telegramChatId: $telegramChatId,
                text: 'пизда',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('0c6351b8-ed69-4a66-8b69-f8342dc3dd86'),
                telegramChatId: $telegramChatId,
                text: 'мать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('d8474a7f-650e-4654-97d6-6fc557265922'),
                telegramChatId: $telegramChatId,
                text: 'сука',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b1cdb00a-30c5-44f0-a61c-9c7f8f0331e1'),
                telegramChatId: $telegramChatId,
                text: 'жопа',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('dacbcbbd-e2f5-40ac-ae72-ef869b88d1e5'),
                telegramChatId: $telegramChatId,
                text: 'анус',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3375ca8f-dfe5-4d8b-9927-cf8b5b057874'),
                telegramChatId: $telegramChatId,
                text: 'ебучий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9eb5fc44-c878-4652-9b40-030bc25850ac'),
                telegramChatId: $telegramChatId,
                text: 'пидор',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('add82e98-41da-4afd-94ac-0cda1fa58018'),
                telegramChatId: $telegramChatId,
                text: 'кал',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ef731295-1f17-4ba2-93ef-0322d736ad46'),
                telegramChatId: $telegramChatId,
                text: 'гавно',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('835f9962-5f59-450b-aa4d-158fe77adb07'),
                telegramChatId: $telegramChatId,
                text: 'вонючий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('832b1fc1-7ffd-4d09-a6df-62c446cf5916'),
                telegramChatId: $telegramChatId,
                text: 'пенис',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a016452f-d145-4f70-96ee-fe4ee2cb1116'),
                telegramChatId: $telegramChatId,
                text: 'член',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b554c06c-d83b-4096-a58f-4c28bd0c0d7a'),
                telegramChatId: $telegramChatId,
                text: 'пиписька',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f207edaa-0e6f-416c-85a4-8ca3f580ec5a'),
                telegramChatId: $telegramChatId,
                text: 'вонючий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bd47575e-39b0-44c5-9880-b7fb9764a43d'),
                telegramChatId: $telegramChatId,
                text: 'немытый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7ec6db0e-ddb7-4f1c-a7c3-5cef6a2a5387'),
                telegramChatId: $telegramChatId,
                text: 'пелотка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('56dfb2b0-58ed-480d-9058-f589d91d5e7f'),
                telegramChatId: $telegramChatId,
                text: 'небритая',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bbbe08da-6a0f-4357-8c33-ac40cc33ff74'),
                telegramChatId: $telegramChatId,
                text: 'онанизм',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8df390d8-b125-4e48-a172-dc792110682e'),
                telegramChatId: $telegramChatId,
                text: 'блядь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('036eb000-3e28-4f4d-9c7f-8f59fd7f82b6'),
                telegramChatId: $telegramChatId,
                text: 'бля',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3d6fa2a1-10a0-4c38-9620-7286fd2d7bd4'),
                telegramChatId: $telegramChatId,
                text: 'очко',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('44f9fa98-fed9-465f-bbef-2587a0f79f46'),
                telegramChatId: $telegramChatId,
                text: 'нефпесда',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('77bd9953-0b64-4850-8205-d5383757d4f5'),
                telegramChatId: $telegramChatId,
                text: 'мандавошка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('398739b8-beae-4a04-aea6-e99e6ff08db9'),
                telegramChatId: $telegramChatId,
                text: 'лобковый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a187c505-dd6d-41f4-83e7-9f840019a6d6'),
                telegramChatId: $telegramChatId,
                text: 'головка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('87b28e53-ecb3-416f-8f8c-6fd8eda56dfc'),
                telegramChatId: $telegramChatId,
                text: 'сцуко',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('1f68a78d-0480-494b-9ada-85ec5dd77333'),
                telegramChatId: $telegramChatId,
                text: 'педрила',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('0ac18b25-5e66-4523-a364-2f14751376a8'),
                telegramChatId: $telegramChatId,
                text: 'злоебучий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a376f207-808e-4bef-8389-b928398acfe7'),
                telegramChatId: $telegramChatId,
                text: 'жопа',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4f2e778f-ea97-481b-9351-6b027d109992'),
                telegramChatId: $telegramChatId,
                text: 'заебаться',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('879cb9a3-ce8d-428e-82d9-cfe50d9e2e29'),
                telegramChatId: $telegramChatId,
                text: 'заебывать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9f11d077-1351-47ef-888e-3b0d29210ab7'),
                telegramChatId: $telegramChatId,
                text: 'комар',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bf471eb7-e3f0-4368-99d6-5e5cc748fea6'),
                telegramChatId: $telegramChatId,
                text: 'ослиный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('d16425cd-a7d3-4615-9508-6270d6bc698c'),
                telegramChatId: $telegramChatId,
                text: 'моча',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6010ceb5-0ba4-465f-bc17-b7429c86d640'),
                telegramChatId: $telegramChatId,
                text: 'ебать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bf7d24bc-8244-488f-8f0f-32a06f1d628e'),
                telegramChatId: $telegramChatId,
                text: 'срака',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('742255a2-ae52-464e-9e80-24b4c87c13e9'),
                telegramChatId: $telegramChatId,
                text: 'злоебучий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a613b76d-172c-42f9-91cb-d136b7afd883'),
                telegramChatId: $telegramChatId,
                text: 'пиздопроебина',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8e48fab4-6e01-4dde-a87b-b038fbec2e56'),
                telegramChatId: $telegramChatId,
                text: 'сиська',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('096b658c-e8ab-4996-b24e-621df0610e30'),
                telegramChatId: $telegramChatId,
                text: 'кобелиный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a25165a1-33c2-46dc-b390-411cb99518b7'),
                telegramChatId: $telegramChatId,
                text: 'позорный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3c7c3c30-d5df-48f3-8b81-5655ba783a73'),
                telegramChatId: $telegramChatId,
                text: 'бобруйск',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('2ca4dbce-3d46-4381-bc9a-9fc3b4fb9cf9'),
                telegramChatId: $telegramChatId,
                text: 'жывотное',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8d0da33a-5c66-493f-8491-c12f39555fd1'),
                telegramChatId: $telegramChatId,
                text: 'доярка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('1eba6079-582b-492d-9957-93fa0649736e'),
                telegramChatId: $telegramChatId,
                text: 'пипирка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6d1f628f-3e58-4558-8a95-779fd80d588e'),
                telegramChatId: $telegramChatId,
                text: 'конский',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b9e4e1ec-678f-4845-b6e4-43073df87670'),
                telegramChatId: $telegramChatId,
                text: 'залупа',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e3db01b6-ba9d-4a0d-904c-144cabc24c6b'),
                telegramChatId: $telegramChatId,
                text: 'урод',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c85c4012-7414-43af-9382-5f16fd74786b'),
                telegramChatId: $telegramChatId,
                text: 'обсираться',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('083b6b4e-4eed-4fbe-935f-851d8edfb267'),
                telegramChatId: $telegramChatId,
                text: 'импотент',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('88c446d3-52b8-46a7-8493-369489cdcd08'),
                telegramChatId: $telegramChatId,
                text: 'сучий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('78213047-4d67-4241-b3ae-5cfc40ca2fff'),
                telegramChatId: $telegramChatId,
                text: 'потрох',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('cdb0263f-541f-41e8-b0ff-bc52b56e8874'),
                telegramChatId: $telegramChatId,
                text: 'жопа',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('fc17fb79-a966-4b49-a2f4-109f7f4598b8'),
                telegramChatId: $telegramChatId,
                text: 'голубой',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e625e9bd-fd47-4d77-9556-cf3ce65c8130'),
                telegramChatId: $telegramChatId,
                text: 'волосатый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f2942a92-afba-4226-95d0-cadb9499efac'),
                telegramChatId: $telegramChatId,
                text: 'ротик',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('38c1e5fb-6d88-4f73-af74-9fb68a825911'),
                telegramChatId: $telegramChatId,
                text: 'дура',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('660e917d-2fe6-4398-804c-ed30b06bea68'),
                telegramChatId: $telegramChatId,
                text: 'импотент',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('16c52dcc-8578-41f2-94a1-bfd464d26b77'),
                telegramChatId: $telegramChatId,
                text: 'пидор',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('fcca336b-28e5-405f-97b0-486c5b782a2c'),
                telegramChatId: $telegramChatId,
                text: 'зловонный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('1f0d9404-d788-4bf0-b093-73c8077c37b7'),
                telegramChatId: $telegramChatId,
                text: 'понос',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('aa9de68c-e1b4-4e23-9d4d-4f8c0df9ab0c'),
                telegramChatId: $telegramChatId,
                text: 'глист',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('518066a3-1ee6-41dc-a857-c3a9734ac0ca'),
                telegramChatId: $telegramChatId,
                text: 'беленький',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('00165a5e-a15e-4f51-88e9-c1b6898fad39'),
                telegramChatId: $telegramChatId,
                text: 'унитаз',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5cc94fd1-62df-440e-bccc-88617c250903'),
                telegramChatId: $telegramChatId,
                text: 'посрать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('eed65e6b-ba62-4af1-ac05-b81030639b4a'),
                telegramChatId: $telegramChatId,
                text: 'срать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a7f703ad-025d-48a8-8338-7d0f88ced54c'),
                telegramChatId: $telegramChatId,
                text: 'ебаный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('51abe0e1-038d-4717-91ab-2f3efa5f74b0'),
                telegramChatId: $telegramChatId,
                text: 'охуевать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b8a63f59-7a40-4ae9-a96f-74d4f6c100ba'),
                telegramChatId: $telegramChatId,
                text: 'сраный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('41b3422a-191c-45ad-ba58-f374cebd464a'),
                telegramChatId: $telegramChatId,
                text: 'мастурбация',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('956f3e2a-ca8b-48ca-91ff-0fd6ed5ff780'),
                telegramChatId: $telegramChatId,
                text: 'убиваться',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('db009717-bc76-4706-86c1-480d9f27b731'),
                telegramChatId: $telegramChatId,
                text: 'онанюга',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('30de5aeb-06a9-47e5-b615-529a36c67625'),
                telegramChatId: $telegramChatId,
                text: 'позорный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9dfe9422-be3c-46ca-994c-5df8ed58308f'),
                telegramChatId: $telegramChatId,
                text: 'рот',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('db6a2299-7ebf-4483-86f8-fa107f96596d'),
                telegramChatId: $telegramChatId,
                text: 'сиська',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('87662189-c0f6-4fc8-b855-22258fc79ce5'),
                telegramChatId: $telegramChatId,
                text: 'писька',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('36e74b2b-3f20-47fd-8dea-9fe9c958d4d1'),
                telegramChatId: $telegramChatId,
                text: 'хуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('1553ab2e-a593-4271-bbac-4345348f271d'),
                telegramChatId: $telegramChatId,
                text: 'уебенить',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('508b6646-42f9-4ab3-b9ec-884afb1ea135'),
                telegramChatId: $telegramChatId,
                text: 'пиздоголовый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f53837fa-d493-4a8b-916a-f8c240011f6b'),
                telegramChatId: $telegramChatId,
                text: 'слоновий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('d5164aa6-c4a7-4bc4-91af-42f088fc1df4'),
                telegramChatId: $telegramChatId,
                text: 'ебнуть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7f972d4b-6551-40ee-a962-1f835626160b'),
                telegramChatId: $telegramChatId,
                text: 'пиздомандовый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4aef8f31-392d-4f1f-b092-f78d2477e190'),
                telegramChatId: $telegramChatId,
                text: 'сракохер',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('12b701a4-d71c-4d17-b112-6014d9a3477a'),
                telegramChatId: $telegramChatId,
                text: 'вафлезалупный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a7335534-42d4-4aea-b908-2b8c9a479aa7'),
                telegramChatId: $telegramChatId,
                text: 'блядопиздища',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('de62a1e7-267a-4df4-bee6-22dc2677d27f'),
                telegramChatId: $telegramChatId,
                text: 'перехуячить',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('fee13634-684b-4a39-ae59-e5c7a5049e4a'),
                telegramChatId: $telegramChatId,
                text: 'хероебливый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('0cbcedee-9ef2-40f9-b376-9e59375c765e'),
                telegramChatId: $telegramChatId,
                text: 'еблезалупище',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a8df5cd1-f7cf-4e80-9f18-2c3f9042449b'),
                telegramChatId: $telegramChatId,
                text: 'сука',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('31bfe539-8fc1-4d43-9f03-ee8d037068f3'),
                telegramChatId: $telegramChatId,
                text: 'ссаный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6061a8d9-f9f4-41c8-8c63-ea018bceffa0'),
                telegramChatId: $telegramChatId,
                text: 'гондон',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a79cd1d9-5f39-40f7-9b05-64423655dd33'),
                telegramChatId: $telegramChatId,
                text: 'штопаный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a7eb3e45-6385-4b8d-a1a9-029c27e4ab61'),
                telegramChatId: $telegramChatId,
                text: 'клиторовна',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('50e93c50-58e7-4915-a0bf-b145f3bd02cc'),
                telegramChatId: $telegramChatId,
                text: 'нехуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8a127768-5eb4-4cc0-b426-9c3cffd68e59'),
                telegramChatId: $telegramChatId,
                text: 'блядь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('aba29449-10e1-4f98-b9cb-a6e3c3c8eaf4'),
                telegramChatId: $telegramChatId,
                text: 'ебнуться',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9d5acbb9-2485-4c7f-9de8-3d2851a897b5'),
                telegramChatId: $telegramChatId,
                text: 'срака',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4c5c079c-1168-458c-ba58-08a4fddd6b35'),
                telegramChatId: $telegramChatId,
                text: 'лошадиный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('1efa262a-f371-436d-94fd-297f00937307'),
                telegramChatId: $telegramChatId,
                text: 'сцукон',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6fbdf8e7-8803-4e70-b83e-900dc30ee884'),
                telegramChatId: $telegramChatId,
                text: 'йад',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4c5be239-ba46-452d-b59b-8e406a9a33e5'),
                telegramChatId: $telegramChatId,
                text: 'невъебенно',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4fe9ebe4-41fc-43c4-b7a9-5d3594210d01'),
                telegramChatId: $telegramChatId,
                text: 'педерестический',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e492fd61-6581-4fff-b068-c0c5645609f3'),
                telegramChatId: $telegramChatId,
                text: 'злоебучесть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('68b33bc0-dda4-4de5-804d-adf69653499e'),
                telegramChatId: $telegramChatId,
                text: 'мудак',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5f49d783-ff5d-4ccd-8fa7-ee818cd91b1f'),
                telegramChatId: $telegramChatId,
                text: 'нехуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('dfce8eed-8a62-4605-a43c-20829df9e337'),
                telegramChatId: $telegramChatId,
                text: 'кончать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('59fb7712-6abe-48c9-baf2-fdc7adeca1a6'),
                telegramChatId: $telegramChatId,
                text: 'пердун',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('64c34a69-de81-4167-8ecc-f55efc9ce28b'),
                telegramChatId: $telegramChatId,
                text: 'сифилитичный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b0ee98dc-129c-4012-9420-f7f576b38b72'),
                telegramChatId: $telegramChatId,
                text: 'бугагага',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8d5d25a0-edf8-4e5b-aea5-813d974a9e5c'),
                telegramChatId: $telegramChatId,
                text: 'пенисович',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('98f2f79f-83b2-4b07-b460-7b4ab2f3602c'),
                telegramChatId: $telegramChatId,
                text: 'писдувать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('2a167c20-254d-449f-89c9-7f8b48f28b6a'),
                telegramChatId: $telegramChatId,
                text: 'кпсс',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('2c2a2a75-1d9d-49b4-953a-d2f2a4a860db'),
                telegramChatId: $telegramChatId,
                text: 'залупень',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c96025a3-40f8-4e3f-9908-c0897e2f3e2a'),
                telegramChatId: $telegramChatId,
                text: 'хитровыебывать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6aad51f8-677d-4860-9225-61beb93fca45'),
                telegramChatId: $telegramChatId,
                text: 'ебля',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ab5a7e79-5cf9-459e-9fb4-944c76607012'),
                telegramChatId: $telegramChatId,
                text: 'педераст',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('63028004-9bd6-465e-801a-0607c8c7702c'),
                telegramChatId: $telegramChatId,
                text: 'хуеть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('154ff14d-c054-4b0a-8255-cd4b089b3502'),
                telegramChatId: $telegramChatId,
                text: 'хуежопый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f3fef11b-ff17-4751-bdf7-1b0e76762200'),
                telegramChatId: $telegramChatId,
                text: 'хуезадый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('0de53f73-1ab2-4265-85e9-e1a036b69f86'),
                telegramChatId: $telegramChatId,
                text: 'хуибалаебанава',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('947e4e24-051f-45fc-817f-23625d0fe476'),
                telegramChatId: $telegramChatId,
                text: 'морской',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7d259c4d-5549-4cd4-a81f-75cf9b93081f'),
                telegramChatId: $telegramChatId,
                text: 'хуйлан',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('60900e42-dc1f-4567-9614-f82b9926faa1'),
                telegramChatId: $telegramChatId,
                text: 'хуйнюшка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7fe2a366-c0b3-4ff0-9772-ae1fb2e65fe8'),
                telegramChatId: $telegramChatId,
                text: 'хуйпизда',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f3b794ef-973f-48f8-b43b-0858d4670601'),
                telegramChatId: $telegramChatId,
                text: 'хуюшка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('497b0c2c-d258-4a42-8f2d-9f03ccaff97f'),
                telegramChatId: $telegramChatId,
                text: 'хуйня',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('41f89f31-11b3-4feb-8b50-6c804c3dc723'),
                telegramChatId: $telegramChatId,
                text: 'хуйлофан',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5e010f22-5625-47fe-a48d-587b6c42d3b9'),
                telegramChatId: $telegramChatId,
                text: 'хуево',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f7ea1089-56b3-48d8-b1eb-98865731c2e0'),
                telegramChatId: $telegramChatId,
                text: 'кукуево',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3ba49668-f367-44b1-835c-058d5accbabf'),
                telegramChatId: $telegramChatId,
                text: 'педерастин',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('95c6aeb0-57f6-4cce-989b-09ca9b68fe39'),
                telegramChatId: $telegramChatId,
                text: 'пердак',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8e8c5299-725e-4e43-8688-eeb7ff025587'),
                telegramChatId: $telegramChatId,
                text: 'пидораска',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6923e069-ac96-42cf-b8a5-5f7f1fb7d9b0'),
                telegramChatId: $telegramChatId,
                text: 'выебывать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b3189c32-1586-45af-99f5-13a30044e95e'),
                telegramChatId: $telegramChatId,
                text: 'пиздлявый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ea7ab3d6-8c7f-4580-ac93-1882d2a2c178'),
                telegramChatId: $telegramChatId,
                text: 'пиздоеб',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('255dc428-c8c9-4030-b56d-b6afb17975c2'),
                telegramChatId: $telegramChatId,
                text: 'пиздокрывать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a45ec0d8-936f-4a7f-be2d-826eb33681f2'),
                telegramChatId: $telegramChatId,
                text: 'еблан',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5b26ca3d-8c06-41ec-bd01-71527179da6d'),
                telegramChatId: $telegramChatId,
                text: 'пиздня',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f191e109-a79d-4f66-857c-f79a6ac3584b'),
                telegramChatId: $telegramChatId,
                text: 'сорочий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('40e2d97b-1565-41d4-90e7-00dd7e24b1a6'),
                telegramChatId: $telegramChatId,
                text: 'пиздувать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4f6a2d8c-3245-47a3-95af-c8dd274c096d'),
                telegramChatId: $telegramChatId,
                text: 'пиздюково',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('2c8a0b17-9f71-481f-b1a0-36e6f311edbb'),
                telegramChatId: $telegramChatId,
                text: 'писька',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('86bcc83a-c00f-4c39-9feb-91b53017f23e'),
                telegramChatId: $telegramChatId,
                text: 'порнопидор',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ce666b86-fa6e-4f26-b68c-2c2c91dd287b'),
                telegramChatId: $telegramChatId,
                text: 'похуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c389481b-8b8c-4db8-973f-8fd634a8f5e8'),
                telegramChatId: $telegramChatId,
                text: 'нахуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c101e1fa-13e3-49a4-a063-87dd07c7b43c'),
                telegramChatId: $telegramChatId,
                text: 'пиздык',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4936f5e5-f333-409c-a860-344bb3c276b9'),
                telegramChatId: $telegramChatId,
                text: 'хуяк',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b035c844-2c6c-4133-9e8f-72a0311195f8'),
                telegramChatId: $telegramChatId,
                text: 'пиздушенция',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('40aa47ed-72d2-4260-aa5b-e32e8701ba5b'),
                telegramChatId: $telegramChatId,
                text: 'переблюд',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b418e6d2-4714-455b-bfe5-d93f7ee7bce6'),
                telegramChatId: $telegramChatId,
                text: 'мохнатый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('53e71b6f-4ba0-447e-97bf-3aae573dd0d7'),
                telegramChatId: $telegramChatId,
                text: 'клитор',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('97343af7-3063-46eb-859f-cad26bac0910'),
                telegramChatId: $telegramChatId,
                text: 'серево',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('551a08e3-5675-40df-ba8c-91beb14073ec'),
                telegramChatId: $telegramChatId,
                text: 'сракохуярище',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a172261c-55bb-4f8c-9459-fb0f56e25f4f'),
                telegramChatId: $telegramChatId,
                text: 'страхопердь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5593b818-d8de-4977-9e47-cfe6a982738b'),
                telegramChatId: $telegramChatId,
                text: 'затыкаться',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3cee3db6-fe9e-49cc-a9ed-993238c3acb8'),
                telegramChatId: $telegramChatId,
                text: 'сукон',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('cb49db15-6633-4acd-9823-286dcf1f0b4d'),
                telegramChatId: $telegramChatId,
                text: 'съебнуть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bd9f22b0-bab9-4755-88f8-880198a37e57'),
                telegramChatId: $telegramChatId,
                text: 'мужчина',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('d20c7789-30e8-48a2-92fb-0fb6c8629fd5'),
                telegramChatId: $telegramChatId,
                text: 'хуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('20461465-ac31-44de-9d46-1c6408018af8'),
                telegramChatId: $telegramChatId,
                text: 'тихобздувать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('55fa0c41-5824-47b9-a763-2f05399e27f7'),
                telegramChatId: $telegramChatId,
                text: 'трандюк',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('22b0ed3d-293b-4003-84ce-89074eded4a3'),
                telegramChatId: $telegramChatId,
                text: 'триждымудоблядскоепиздопро',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e2937e53-ad85-4e7a-8de6-dd740a2e54bd'),
                telegramChatId: $telegramChatId,
                text: 'триждыблятский',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c6802997-c956-4684-b501-87a5b32e3942'),
                telegramChatId: $telegramChatId,
                text: 'промондовошино',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('81f22ff6-d15a-4fa5-8542-e584ea3e464f'),
                telegramChatId: $telegramChatId,
                text: 'триебучий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('4200f683-0a85-41a6-bdff-0f5db2e88b7d'),
                telegramChatId: $telegramChatId,
                text: 'проебенить',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('96aa8d0d-b91c-4d58-b8af-6013e1ba6323'),
                telegramChatId: $telegramChatId,
                text: 'тухлогрудый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('89de6afb-fd6a-45ea-8f60-8dd2bd17de9a'),
                telegramChatId: $telegramChatId,
                text: 'бандерлога',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('dd3ffd6b-b708-459b-8bfb-c49784ada18a'),
                telegramChatId: $telegramChatId,
                text: 'придурок',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8f391d24-83fc-4e61-80a8-8ecf0768bc60'),
                telegramChatId: $telegramChatId,
                text: 'отставать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('18191980-31a6-4772-9566-9ec286593bc8'),
                telegramChatId: $telegramChatId,
                text: 'развитие',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f1ba7fae-38d1-4015-a2b5-9556d3b56db3'),
                telegramChatId: $telegramChatId,
                text: 'выебывать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a3938eb6-1712-473b-8f05-1a812cae7c97'),
                telegramChatId: $telegramChatId,
                text: 'допиздиш',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b3fa8a5c-2394-42a2-bf6f-489e0e1ef0dd'),
                telegramChatId: $telegramChatId,
                text: 'алапездырь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a66dc7e4-83ad-4a4e-893e-ccf79487e670'),
                telegramChatId: $telegramChatId,
                text: 'пассивный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9b7cec9e-35b1-480e-935f-52d731ef07b6'),
                telegramChatId: $telegramChatId,
                text: 'педик',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('10467520-6d08-4e96-b73e-176d99ef9bc7'),
                telegramChatId: $telegramChatId,
                text: 'лошин',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('327d3aca-82de-444d-ba9f-375be789f474'),
                telegramChatId: $telegramChatId,
                text: 'ебаный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a353ee9e-6ad7-4da9-b34e-5b86b84304a2'),
                telegramChatId: $telegramChatId,
                text: 'лупиздень',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bae0f63a-5325-4847-a792-f3efdff64a41'),
                telegramChatId: $telegramChatId,
                text: 'живоглотка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('55fddcf5-f336-4763-8b92-eeda3fef7dd4'),
                telegramChatId: $telegramChatId,
                text: 'обдолбать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('36e7fc28-10a3-450c-9c57-42717d17337b'),
                telegramChatId: $telegramChatId,
                text: 'ниггер',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8da6104f-67c4-40f3-af2f-bf90990a5d64'),
                telegramChatId: $telegramChatId,
                text: 'облямандавевший',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b1b35184-8101-4aa2-8707-6474f180e636'),
                telegramChatId: $telegramChatId,
                text: 'пиздопроушина',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('cce793f2-44d4-4c80-81bb-5419ad86d466'),
                telegramChatId: $telegramChatId,
                text: 'однохуйственно',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('d73308dd-23ef-451f-9a4d-0b349203ed9f'),
                telegramChatId: $telegramChatId,
                text: 'здух',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ac9a9fcb-be36-46f2-8b39-e58f56149794'),
                telegramChatId: $telegramChatId,
                text: 'охуепиздрически',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7db1b7d1-ca76-4dea-87e7-a8cef75a3f09'),
                telegramChatId: $telegramChatId,
                text: 'насрать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c1db2f5e-7e41-4f4f-bfae-46feebb4a4b2'),
                telegramChatId: $telegramChatId,
                text: 'компот',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3f3a6d8c-1df4-4bd4-8c83-5e4444b9dc3a'),
                telegramChatId: $telegramChatId,
                text: 'пизда',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('45f9d04d-5873-43db-8347-42d559935c9a'),
                telegramChatId: $telegramChatId,
                text: 'малолетний',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8243e21e-6d96-44dd-bfa1-6d634fa3f4b1'),
                telegramChatId: $telegramChatId,
                text: 'хуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('06869479-6571-48fb-b4e4-a267969206a6'),
                telegramChatId: $telegramChatId,
                text: 'охуевать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9b2c30ed-03f4-4987-a36c-80a232836f51'),
                telegramChatId: $telegramChatId,
                text: 'яйцо',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5d958c5d-404e-4b91-9611-f783d2aac1e1'),
                telegramChatId: $telegramChatId,
                text: 'точно',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('a8cc0b26-ea6c-41bf-ab3d-c27562462115'),
                telegramChatId: $telegramChatId,
                text: 'пизда',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c5fcf422-b206-4d8b-ada0-1b5b4cafe259'),
                telegramChatId: $telegramChatId,
                text: 'блябуда',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ed86e705-3e22-4627-a432-3b9090a73ce4'),
                telegramChatId: $telegramChatId,
                text: 'бляпиздец',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ebda62b7-a052-443e-a326-a756294f1ba6'),
                telegramChatId: $telegramChatId,
                text: 'хуеть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('788acf08-cb1d-40cb-af39-c2668b625d45'),
                telegramChatId: $telegramChatId,
                text: 'кочерышко',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('29924530-4b0b-4739-95c8-b540c4a2230c'),
                telegramChatId: $telegramChatId,
                text: 'мышь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c8211834-369e-44b1-8087-e06f7a265ff0'),
                telegramChatId: $telegramChatId,
                text: 'ясенхуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8306e66f-18bd-4249-a67f-36331ca6790d'),
                telegramChatId: $telegramChatId,
                text: 'жопа',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bee8cc3d-91c5-43c3-a31d-1a49032d314a'),
                telegramChatId: $telegramChatId,
                text: 'эрогенный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f363cae1-4e2a-4371-9aee-b01936e4d133'),
                telegramChatId: $telegramChatId,
                text: 'ебать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('421b1ad8-34c7-44cb-b002-2fcb2ae5fdb1'),
                telegramChatId: $telegramChatId,
                text: 'ымля',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f2057317-c16f-4a70-8210-7d96e2d0da15'),
                telegramChatId: $telegramChatId,
                text: 'емль',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('649b55d6-5741-45e2-909c-bb4f7ca45bd5'),
                telegramChatId: $telegramChatId,
                text: 'шантрепиздюция',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('32166af8-7fc3-4697-926e-c566e0c55420'),
                telegramChatId: $telegramChatId,
                text: 'дырка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('ef43f5b9-749d-4399-a8b7-75ac6f4c57d3'),
                telegramChatId: $telegramChatId,
                text: 'четырехмудоблядыйпиздохуй',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('f4c5e1aa-7af9-4b8f-b5c9-c017c96f5dea'),
                telegramChatId: $telegramChatId,
                text: 'членососательный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('36e23afe-7f17-42f0-9b22-ef3e9c3cc9bf'),
                telegramChatId: $telegramChatId,
                text: 'чмопиздрокл',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e0fd4cd6-b66a-4e95-8707-c7e0d36228dc'),
                telegramChatId: $telegramChatId,
                text: 'педераст',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('2f7eaee8-eb8b-4446-9e65-45b708e48d3d'),
                telegramChatId: $telegramChatId,
                text: 'ебнуть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e684ef4a-2798-4f09-a7a8-e95859c0755e'),
                telegramChatId: $telegramChatId,
                text: 'придурок',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('c57c1e4f-77dc-411a-972f-5290d29d7f0d'),
                telegramChatId: $telegramChatId,
                text: 'пиздануть',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('46cb0d71-eda2-4821-9728-adb184271743'),
                telegramChatId: $telegramChatId,
                text: 'аграхуйный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7df3d93c-0b9d-4295-bc0f-40f8aa983370'),
                telegramChatId: $telegramChatId,
                text: 'мразь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e5c49ba6-1b11-40f7-b284-2a30f0bc040b'),
                telegramChatId: $telegramChatId,
                text: 'затычка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('d031a92c-0476-436c-8115-9c79d8b7dce5'),
                telegramChatId: $telegramChatId,
                text: 'мама',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('0d6cb5ca-0858-455f-bfc5-a536c6717cbc'),
                telegramChatId: $telegramChatId,
                text: 'ебучий',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('b005c5a1-826b-4c01-8a97-bbcf5185663b'),
                telegramChatId: $telegramChatId,
                text: 'пурга',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('bacd7906-bdba-41ba-b45d-a4455d3a18f8'),
                telegramChatId: $telegramChatId,
                text: 'образина',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('e812237f-504b-4c38-924e-ca7d5a91f951'),
                telegramChatId: $telegramChatId,
                text: 'малолетка',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('37e8b738-d142-42dc-8044-2e48c6d56fe0'),
                telegramChatId: $telegramChatId,
                text: 'узкоглазый',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('6af456b0-043f-475c-8b59-9313802abae7'),
                telegramChatId: $telegramChatId,
                text: 'шлюха',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('2a1fe5e3-e0d7-4fbc-9593-232baa08410f'),
                telegramChatId: $telegramChatId,
                text: 'неквалифицированный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('1e305a7b-36ec-4803-b71d-87c9c3f0925a'),
                telegramChatId: $telegramChatId,
                text: 'минет',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('da52b051-8abe-4840-ba29-3d808438f5f8'),
                telegramChatId: $telegramChatId,
                text: 'делать',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('3d8b1865-20ac-4137-9203-b94a67cf1174'),
                telegramChatId: $telegramChatId,
                text: 'тварь',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('7791c3be-89d6-466a-88f6-bf3151863d2a'),
                telegramChatId: $telegramChatId,
                text: 'предменструальный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('8cf4a3fb-daeb-4721-b288-d2f86cb5d9d8'),
                telegramChatId: $telegramChatId,
                text: 'период',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('9a45c513-82ef-43ad-829b-4f31cc0b4120'),
                telegramChatId: $telegramChatId,
                text: 'лобкотряска',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('96321e46-2470-4f1d-9fc8-1a0bb9de35b8'),
                telegramChatId: $telegramChatId,
                text: 'вафельный',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
            new BadWordLibraryRecord(
                id: Uuid::fromString('5bc43a50-229b-401f-bd0e-985f626076ba'),
                telegramChatId: $telegramChatId,
                text: 'пуджа',
                telegramMessageId: null,
                active: true,
                updatedAt: null,
            ),
        ];
    }
}
