version: "3.7"
services:
  nginx:
    image: nikitades/toxic-avenger-bot-nginx:latest
    ports:
      - "8085:80"
    depends_on:
      - fpm
    links:
      - fpm
  fpm:
    image: nikitades/toxic-avenger-bot-php-fpm:latest
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./var:/var/www/html/var
  redis:
    image: redis:6.0.8-alpine
    volumes: 
      - ./redis-db:/data